development:
  adapter: postgresql
  database: pp_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: pp_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: pp_production
  pool: 5
  timeout: 5000
