Member.delete_all
Member.create([
        { name: 'Arnold Yoon', email: "HeyArnold@mail.com" },
        { name: 'Dana Larson', email: "ilikebeach@mail.com" },
        { name: 'Brad Soroka', email: "EastCoastDiego@mail.com" },
        { name: 'Jessica Moon', email: "GamingVigilante@mail.com" },
        { name: 'Rocky Roark', email: "NerdzorDoodler@mail.com" },
        { name: 'Jamie Hamel-Smith', email: "nerd^3D@mail.com" },
        { name: 'Dave Shepard', email: "BeardedDev@mail.com" },
        { name: 'Jason Amunwa', email: "productNinja@mail.com" },
        { name: 'Brian Bimschleger', email: "white-surf-boards@mail.com" },
        { name: 'Brent Summers', email: "musicRacer@mail.com" },
        { name: 'Cody Iddings', email: "NintendoHawaiian@mail.com" },
        { name: 'Annie Sexton', email: "CoffeeTexan@mail.com" },
        { name: 'Dan Birman', email: "buffPainter@mail.com" },
        { name: 'Melanie Chandruang', email: "QuickbookNinja@mail.com" },
        { name: 'Dani Dufrene', email: "ScooooDucks@mail.com" },
        { name: 'Bethany Brown', email: "saltLakeCode@mail.com" },
        { name: 'Allison Drake', email: "advloAccountHolder@mail.com" },
        { name: 'Dustin Lamont', email: "cornDogger@mail.com"  },
        { name: 'MK Cook', email: "beePizza@mail.com"  },
        { name: 'Ben Thiefels', email: "VTproud@mail.com" },
        { name: 'Eric Thomas', email: "electronJams@mail.com" },
        { name: 'Susie Pollasky', email: "storytellerTime@gmail.com" },
        { name: 'Jimmy Ebeling', email: "chikenEatr@mail.com" },
        { name: 'Marc Caldwell', email: "OceanSushi@mail.com" },
        { name: 'Bradley Kenyon', email: "desToDev@mail.com" },
        { name: 'Chuck Longanecker', email: "CoolEverythingOperator@mail.com" },
        { name: 'Orville Esoy', email: "Wanderluster@mail.com" },
        { name: 'Maurice Rosemond', email: "GeorgianThinkr@mail.com" },

        { name: 'DAN TRENKNER', email: "AdvloGuy@mail.com" },
        { name: 'SHANNON LONGANECKER', email: "FarmerMarketr@mail.com" },
        { name: 'SHAWN LESLIE', email: "sunglasser@mail.com" },
        { name: 'JOHN BOTICA', email: "BeerBrewer@mail.com" },
        { name: 'ARON SCHUHMANN', email: "shredderWithPurpose@mail.com" },
        { name: 'NATE SONNENBERG', email: "DigitalGuy@mail.com" },
        { name: 'LAURENCE MONTGOMERY', email: "WSP4LYFE@mail.com" },
        { name: 'SAM ANDERSON', email: "PRtoTacos@mail.com" },
        { name: 'DAVID NGUYEN', email: "DaServicer@mail.com" },
        { name: 'BRIAN BURKETT', email: "twitterFriend@mail.com" },
        { name: 'NATE SONNENBERG', email: "DigitalGuy@mail.com" },
        { name: 'Sara', email: "Dog1@mail.com" },
        { name: 'Paisely', email: "dog2@mail.com" },
        { name: 'Kibah', email: "dog3@mail.com" },
        { name: 'luna', email: "moonDoggie@mail.com" }
])
