Member.delete_all
Member.create([
        { name: 'Rick Astly', email: "rickrolled@mail.com" },
        { name: 'Derek Torr', email: "manager@mail.com" },
        { name: 'Cam Merra', email: "photos@mail.com" },
        { name: 'Devin Chee', email: "sistine@mail.com" },
        { name: 'Blair Ring', email: "music@mail.com" },
        { name: 'Sampson Night', email: "suitcase@mail.com" },
        { name: 'Laurie Aught', email: "nobel@mail.com" },
        { name: 'Eley Feighnt', email: "postgresql@mail.com" },
        { name: 'Chance Hellor', email: "government@mail.com" },
        { name: 'Dan Deelions', email: "flowers@mail.com" },
        { name: 'Abdul Chaudrhy', email: "abdul@mail.com" },
        { name: 'Devin Foley', email: "mboileman@mail.com" },
        { name: 'Jeff Lee', email: "jlee@mail.com" },
        { name: 'Kevin Ebaugh', email: "keshaluvr@mail.com" },
        { name: 'Lady', email: "pooch@mail.com" },
        { name: 'Sloane Sturzenegger', email: "thecodernator@mail.com" },
        { name: 'Leor Stern', email: "lordleor@mail.com" },
        { name: 'Linden Tibbets', email: "tibetbro@mail.com"  },
        { name: 'Nate Murray', email: "catluvr@mail.com"  },
        { name: 'Shiva Kilaru', email: "supreme_god@mail.com" },
        { name: 'Alexander Tibbets', email: "tidbits@mail.com" },
        { name: 'Christopher Knight', email: "rehpotsirhc46@gmail.com" },
        { name: 'Anthony Accomazzo', email: "anthony@ifttt.com" }
])